collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3138992
  lightness: 0.7038246
  brandColors:
    - '#191919'
    - '#494949'
    - '#FFFFFF'
    - '#999999'
    - '#BEBEBE'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 0.9057836
name: Dadgum Media Group
