collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#020300'
    - '#575350'
    - '#D3D5E2'
    - '#6A829C'
    - '#C27757'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 0.4197761
name: Dadgum Media Group
