collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4869403
color:
  saturation: 0
  brandStrength: 0.9295709
  lightness: 0.7038246
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#896849'
    - '#C0A590'
    - '#910000'
  rhythmicContrast: 1
layout_spectrum: 0.6823694
name: Dadgum Media Group
