collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7210821
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#DDDDDD'
    - '#5B5B5B'
    - '#111111'
    - '#787878'
  rhythmicContrast: 0.7728545
typography_spectrum: 0.4869403
layout_spectrum: 0.2938433
name: Dadgum Media Group
