collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.6777052
  lightness: 1
  brandColors:
    - '#D7CFAB'
    - '#161A33'
    - '#507C99'
    - '#ECF4FF'
    - '#685355'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 0
name: Dadgum Media Group
