collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.4463619
  lightness: 1
  brandColors:
    - '#111312'
    - '#DDE2DE'
    - '#908F8B'
    - '#404548'
    - '#28A5B3'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 0.4197761
name: Dadgum Media Group
