collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.4458955
  lightness: 0.7038246
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#81302F'
    - '#747A78'
    - '#E18384'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 1
name: Dadgum Media Group
