collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4869403
color:
  saturation: 0
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FEFEFE'
    - '#010101'
    - '#E40100'
    - '#FDFE02'
    - '#317985'
  rhythmicContrast: 1
layout_spectrum: 0.4197761
name: Dadgum Media Group
