collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3138992
  rhythmicContrast: 1
  brandColors:
    - '#E0D8B4'
    - '#AEA88C'
    - '#FDCC04'
    - '#3A3B36'
    - '#100F0B'
  lightness: 0.7038246
typography_spectrum: 0.4869403
layout_spectrum: 0.3498134
name: Dadgum Media Group
