collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.7038246
  brandColors:
    - '#000000'
    - '#FBFBFB'
    - '#6C6C6C'
    - '#5A3213'
    - '#F193A0'
  rhythmicContrast: 1
typography_spectrum: 0.4869403
layout_spectrum: 0.3941231
name: Dadgum Media Group
