collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8423507
color:
  saturation: 0
  brandStrength: 0.4458955
  lightness: 0.5415112
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#81302F'
    - '#747A78'
    - '#E18384'
  rhythmicContrast: 1
layout_spectrum: 0.2653918
name: Dadgum Media Group
