collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1916978
  brandStrength: 0.7523321
  lightness: 0.7308769
  brandColors:
    - '#FFFFFF'
    - '#949494'
    - '#443838'
    - '#FF0013'
    - '#6CC9DA'
  rhythmicContrast: 0.7728545
typography_spectrum: 0.4869403
layout_spectrum: 0.2938433
name: Dadgum Media Group
